"""empty message

Revision ID: 13b88aae4884
Revises: 18df191fbe08
Create Date: 2020-10-07 08:58:38.296551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b88aae4884'
down_revision = '18df191fbe08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_dribbble_reg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_dribbble_reg')
    # ### end Alembic commands ###
