"""empty message

Revision ID: 4575b0c0fb58
Revises: 8c817fa7c62a
Create Date: 2020-10-06 22:26:55.851502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4575b0c0fb58'
down_revision = '8c817fa7c62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('up_work')
    op.drop_column('task', 'is_comment_task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_comment_task', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('up_work',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('work_type', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='up_work_pkey')
    )
    # ### end Alembic commands ###
